# -*- coding: utf-8 -*-
#: Object types for object ids
object_type = {
    "null": 0,
    "base": 1,
    "account": 2,
    "asset": 3,
    "force_settlement": 4,
    "committee_member": 5,
    "witness": 6,
    "limit_order": 7,
    "call_order": 8,
    "custom": 9,
    "proposal": 10,
    "operation_history": 11,
    "withdraw_permission": 12,
    "vesting_balance": 13,
    "worker": 14,
    "balance": 15,
    "htlc": 16,
    "custom_authority": 17,
    "ticket": 18,
    "liquidity_pool": 19,
    "OBJECT_TYPE_COUNT": 19,
}
